name: Setup Node with Yarn Dependencies
description: Reusable composition of setup-node, cache, and yarn install actions
inputs:
  force-install:
    description: When 'true', yarn install will be executed regardless of a cache hit
    required: false
    default: 'false'
outputs:
  cache-hit:
    description: Whether or not there was a cache hit
    value: ${{ steps.dependency-cache.outputs.cache-hit }}
runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: '14.18.0'

    - name: Dependency Cache
      id: dependency-cache
      uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: yarn-14.18.0-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Install Dependencies
      if: ${{ inputs.force-install == 'true' || steps.dependency-cache.outputs.cache-hit != 'true' }}
      shell: bash
      run: |
        yarn --frozen-lockfile --production=false