[build]
  base = "hello-world"
  publish = "dist/"
  command = "yarn run build"

[functions]
  directory = "netlify/functions/lib"

[[redirects]]
  from = "/api/*"
  to = "/"
  status = 418

[[redirects]]
  from = "/health/*"
  to = "/"
status = 204