name: actions wrokflow

on:
  push:
    branches:
      - first-workflow
  pull_request:
    types: ["opened"]
    branches:
      - first-workflow

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: |
          pwd
          ls  -la
          echo "github sha ${GITHUB_SHA}"
          echo "github ref ${GITHUB_REF}"

      - name: checkout
        uses: actions/checkout@v1

      - name: list files after checkout
        run: |
          pwd
          ls  -la

      - name: simple js action
        id: greet
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: 'devon'

      - name: log greeting time
        run: echo "${{ steps.greet.outputs.time }}"