name: simple dispatch

on:
# repository_dispatch runs from default branch... https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#repository_dispatch
  repository_dispatch:
    types: [foo, bar]

jobs:
  run-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: list payload
        run: echo ${{ github.event.client_payload }}
