name: simple dispatch

on:
  repository_dispatch:
    types: [foo, bar]
    branches:
      - '*'

jobs:
  run-dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: list payload
        run: echo ${{ github.event.client_payload }}
