name: test things
on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: test fetch tags
        id: fetch-tags
        run: |
          git fetch --tags
          git fetch --prune --unshallow || true

          echo $(git tag)

          LATEST_A_VER=$(git describe --match "a-*" --abbrev=0 --tags 2>/dev/null)

          echo "latest a version: ${LATEST_A_VER}"

          [[ -z ${LATEST_A_VER} ]] && echo "initial ver" || echo ${LATEST_A_VER}

          LATEST_B_VER=$(git describe --match "b-*" --abbrev=0 --tags main 2>/dev/null)

          echo "latest b version: ${LATEST_B_VER}"

          [[ -z ${LATEST_A_VER} ]] && echo "initial ver" || echo ${LATEST_B_VER}

          LATEST_F_VER=$(git describe --match "f-*" --abbrev=0 --tags main 2>/dev/null)

          echo "latest f version: ${LATEST_F_VER}"
          
          [[ -z ${LATEST_F_VER} ]] && echo "initial ver" || echo ${LATEST_F_VER}
