name: test things
on: push

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2

      - name: test fetch tags
        id: fetch-tags
        run: |
          git fetch --tags
          git fetch --prune --unshallow || true
          
          echo $(git tag)

          git describe --match "a-*" --abbrev=0 --tags
