name: upload_download_test
on: push

jobs:
  upload_some_stuff:
    name: upload_artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: create artifact a
        id: create_art_a
        run: |
          mkdir -p artifacts/art_a/dist && touch artifacts/art_a/dist/{a..f}.txt
          tar -czvf artifacts/art_a.tar.gz artifacts/art_a/

      - name: create artifact b
        id: create_art_b
        run: |
          mkdir -p artifacts/art_b/dist && touch artifacts/art_b/dist/{a..f}.txt
          tar -czvf artifacts/art_b.tar.gz artifacts/art_b

      - name: Temporarily save artifact
        uses: actions/upload-artifact@v2
        id: upload
        with:
          name: artifacts
          path: artifacts

  download_some_stuff:
    name: download_artifacts
    needs: upload_some_stuff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: download_artifacts
        uses: actions/download-artifact@v2
        id: download_artifacts
        with:
          name: artifacts

      - name: inspect
        id: inspect
        run: |
          ls -R

  do_some_stuff:
    name: do_some_stuff
    needs: upload_some_stuff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: download_artifacts
        uses: actions/download-artifact@v2
        id: download_artifacts
        with:
          name: artifacts
# the leading folder 'artifacts' gets stripped
      - name: extract_art_b
        id: extract_art_b
        run: |
          mkdir artifact_b_extracted
          tar -xvzf art_b.tar.gz -C artifact_b_extracted
          ls artifact_b

      - name: inspect_all
        id: inspect_all
        run: |
          ls -R


